name: gallery_cleaner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1
  image: ^4.2.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  jiffy: ^6.3.1
  modal_progress_hud_nsn: ^0.5.1
  photo_gallery: ^2.2.1
  photo_manager: ^3.1.1
  photo_manager_image_provider: ^2.1.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  tflite_flutter: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/tflite/model.tflite
    - assets/tflite/labels.txt
